// KI Welt — copy in DE + EN
export const COPY = {
  de: {
    nav: { home: "Start", services: "Leistungen", process: "Vorgehen", faq: "FAQ", contact: "Kontakt", cta: "Beratung buchen" },
    eyebrow: "KI Welt — Maßgeschneiderte KI für Unternehmen",
    primary: "Kostenlose Beratung buchen",
    secondary: "Alle Leistungen",
    nowLabel: "Anwendungsfall",
    beforeLabel: "Vorher",
    afterLabel: "Nachher",
    slides: [
      {
        tag: "Dokumenten­verarbeitung",
        h1Pre: "Aus Papierstapeln werden",
        h1Em: "Briefing-Mappen.",
        lede: "Eingang, OCR, strukturierte Zusammen­fassung, Auto-Routing zur richtigen Abteilung — mit Quellen­zitaten.",
        before: { label: "Vorher — manuell", value: "≈ 4 Std / Stapel" },
        after:  { label: "Nachher — KI Welt", value: "≈ 90 Sek / Stapel" },
      },
      {
        tag: "Kundenservice",
        h1Pre: "Ein Chat, der",
        h1Em: "wirklich handeln darf.",
        lede: "Ein Agent mit Zugriff auf Zahlung, CRM, E‑Mail und Versand. Antwortet, eskaliert klug, dokumentiert lückenlos.",
        before: { label: "Vorher — Hotline", value: "≈ 18 Min Wartezeit" },
        after:  { label: "Nachher — Agent", value: "≈ 22 Sek Erstantwort" },
      },
      {
        tag: "Sicherheit & Code",
        h1Pre: "Schwachstellen finden,",
        h1Em: "bevor andere sie finden.",
        lede: "Kontinuierliche Analyse statt Quartals-Audit. Priorisiert nach Ausnutzbarkeit — mit fertigen Pull-Requests.",
        before: { label: "Vorher — manuell", value: "1 × pro Quartal" },
        after:  { label: "Nachher — Audit", value: "Alle 4 Stunden" },
      },
      {
        tag: "Maßgeschneidert",
        h1Pre: "Vom Problem zum",
        h1Em: "eigenen Werkzeug.",
        lede: "Wir bauen die Anwendung — mit oder ohne KI — exakt für Ihren Prozess. Sauber dokumentiert, dann übergeben.",
        before: { label: "Vorher — Tool-Salat", value: "Excel-Stand: Donnerstag" },
        after:  { label: "Nachher — Eigenanwendung", value: "Live, Single Source" },
      },
    ],
    services: {
      kicker: "Was wir bauen",
      title: "Vier Wege, wie wir Ihr Unternehmen umbauen.",
      sub: "Jedes Engagement startet mit zwei Wochen Diagnose. Was danach kommt, hängt vom Engpass ab — nicht vom Pitchdeck.",
      items: [
        { num: "01", title: "Prozess‑Automatisierung", body: "Dokumente, Formulare, Genehmigungen. Wir messen die Workflow‑Zeit, ersetzen Klick‑Arbeit durch Pipelines und behalten den Menschen dort, wo er entscheidet.", tags: ["OCR", "Workflows", "RPA", "Human‑in‑the‑Loop"] },
        { num: "02", title: "KI‑Agenten & Chat", body: "Kunden­service, internes Wissens­management, Sales‑Assistenz. Mit echtem Tool‑Zugriff (Zahlung, CRM, ERP).", tags: ["LLM", "Tool‑Use", "RAG", "Voice"] },
        { num: "03", title: "Sicherheit & Code‑Audit", body: "Penetration‑Test, Code‑Review, Abhängigkeits­scan, kontinuierliches Monitoring. Mit konkreten Pull‑Requests.", tags: ["Pentest", "SAST/DAST", "Supply‑Chain", "SOC2"] },
        { num: "04", title: "Custom Software", body: "Wenn von der Stange nicht passt: wir bauen die Anwendung, das Dashboard, die Integration. Sauber dokumentiert, dann übergeben.", tags: ["Web", "Mobile", "Datenplattform", "Integrationen"] },
      ],
    },
    process: {
      kicker: "Vorgehen",
      title: "In 90 Tagen vom Engpass zum Pilot.",
      sub: "Festpreis‑Diagnose vorab. Danach iterativ — Sie entscheiden nach jedem Schritt, ob es weitergeht.",
      steps: [
        { num: "01", title: "Diagnose", body: "Zwei Wochen vor Ort. Wir vermessen Prozesse, sprechen mit den Teams, bewerten den Code. Ergebnis: priorisierte Roadmap.", time: "Wo 1 – 2" },
        { num: "02", title: "Prototyp", body: "Schlankster Schnitt durchs Problem. Funktioniert in Ihrer Umgebung mit echten Daten.", time: "Wo 3 – 6" },
        { num: "03", title: "Rollout", body: "Schrittweise Einführung pro Abteilung. Telemetrie, Schulung, Feedback‑Loop. Wir bleiben dran.", time: "Wo 7 – 12" },
        { num: "04", title: "Übergabe", body: "Sauberer Code, Dokumentation, optional Wartungs­vertrag. Ihr Team kann selbst weiterbauen.", time: "ab Wo 13" },
      ],
    },
    faq: {
      kicker: "FAQ",
      title: "Was Sie wahrscheinlich fragen wollten.",
      items: [
        { q: "Müssen wir alle Daten an einen externen LLM‑Anbieter geben?", a: "Nein. Wir hosten standardmäßig in der EU und arbeiten mit selbstgehosteten Modellen, wenn Compliance es verlangt. Bei Bedarf vollständig on‑premise." },
        { q: "Was, wenn KI gar nicht die richtige Antwort ist?", a: "Dann schlagen wir keine vor. Etwa die Hälfte unserer Engagements endet mit klassischer Software, besseren Workflows oder einem Integrations‑Layer." },
        { q: "Wie sieht die Preisgestaltung aus?", a: "Festpreis für die Diagnose (typisch 12–25k €). Danach Werkvertrag pro Modul oder Time‑and‑Material. Erstgespräch und Roadmap‑Skizze sind kostenlos." },
        { q: "Übernehmen Sie auch den Betrieb?", a: "Optional. Drei Modelle: vollständige Übergabe, geteilte Verantwortung mit On‑Call, oder Managed Service mit SLA. Ohne Lock‑in — der Code gehört Ihnen." },
        { q: "Welche Branchen?", a: "Mittelstand, Industrie, Gesundheit, Finanzdienstleister, Logistik. Wir lehnen Projekte ab, bei denen wir keine relevante Erfahrung mitbringen." },
      ],
    },
    contact: {
      kicker: "Kontakt",
      title: "Sprechen wir 30 Minuten.",
      body: "Erstgespräch unverbindlich. Wenn passt, schicken wir Ihnen innerhalb von 5 Werktagen eine grobe Roadmap und ein Festpreis‑Angebot.",
      checks: ["Antwort innerhalb 24 Std", "NDA bei Bedarf vor dem Gespräch", "Kein Verkaufsdruck"],
      f: { name: "Name", company: "Unternehmen", email: "E‑Mail", phone: "Telefon (optional)", topic: "Thema", topicOpts: ["Prozess‑Automatisierung", "Chat / KI‑Agent", "Sicherheits‑Audit", "Custom Software", "Etwas anderes"], message: "Worum geht es?", messagePh: "Beschreiben Sie kurz den Engpass.", submit: "Termin anfragen", thanks: "Danke — wir melden uns innerhalb von 24 Stunden." },
    },
    footer: { copy: "© 2026 KI Welt GmbH — Hosting in Frankfurt a. M.", links: ["Impressum", "Datenschutz", "Karriere"] },
  },

  en: {
    nav: { home: "Home", services: "Services", process: "Process", faq: "FAQ", contact: "Contact", cta: "Book a consultation" },
    eyebrow: "KI Welt — Custom AI for serious companies",
    primary: "Book a free consultation",
    secondary: "All services",
    nowLabel: "Use case",
    beforeLabel: "Before",
    afterLabel: "After",
    slides: [
      {
        tag: "Document processing",
        h1Pre: "Stacks of paper become",
        h1Em: "briefing folders.",
        lede: "Inbox, OCR, structured summary, auto-routing to the right department — with source citations.",
        before: { label: "Before — manual", value: "≈ 4h per batch" },
        after:  { label: "After — KI Welt", value: "≈ 90s per batch" },
      },
      {
        tag: "Customer service",
        h1Pre: "A chat that's actually",
        h1Em: "allowed to act.",
        lede: "One agent with access to payments, CRM, email, shipping. Answers, escalates intelligently, documents every step.",
        before: { label: "Before — hotline", value: "≈ 18 min wait" },
        after:  { label: "After — agent", value: "≈ 22s first reply" },
      },
      {
        tag: "Security & code",
        h1Pre: "Find the holes",
        h1Em: "before anyone else does.",
        lede: "Continuous analysis instead of quarterly audits. Prioritized by exploitability — with ready-to-merge pull requests.",
        before: { label: "Before — manual", value: "1× per quarter" },
        after:  { label: "After — audit", value: "every 4 hours" },
      },
      {
        tag: "Bespoke",
        h1Pre: "From problem to",
        h1Em: "your own tool.",
        lede: "We build the application — with or without AI — sized exactly for your process. Documented, then handed over.",
        before: { label: "Before — tool soup", value: "Excel as of: Thursday" },
        after:  { label: "After — own app", value: "live, single source" },
      },
    ],
    services: {
      kicker: "What we build",
      title: "Four ways we rewire your company.",
      sub: "Every engagement starts with a two‑week diagnostic. What follows depends on the bottleneck — not on the pitch deck.",
      items: [
        { num: "01", title: "Process automation", body: "Documents, forms, approvals. We measure the workflow time, replace click-work with pipelines, and keep humans where they decide.", tags: ["OCR", "Workflows", "RPA", "Human-in-the-loop"] },
        { num: "02", title: "AI agents & chat", body: "Customer support, internal knowledge, sales assistance. With actual tool access (payments, CRM, ERP).", tags: ["LLM", "Tool-use", "RAG", "Voice"] },
        { num: "03", title: "Security & code audit", body: "Penetration test, code review, dependency scan, continuous monitoring. With concrete pull requests.", tags: ["Pentest", "SAST/DAST", "Supply-chain", "SOC2"] },
        { num: "04", title: "Custom software", body: "When off-the-shelf doesn't fit: we ship the application, the dashboard, the integration. Documented, then handed over.", tags: ["Web", "Mobile", "Data platform", "Integrations"] },
      ],
    },
    process: {
      kicker: "How we work",
      title: "From bottleneck to pilot in 90 days.",
      sub: "Fixed-price diagnostic up front. After that, iterative — you decide at every milestone.",
      steps: [
        { num: "01", title: "Diagnose", body: "Two weeks on site. We measure processes, talk to teams, review the code. Output: a prioritized roadmap.", time: "wks 1–2" },
        { num: "02", title: "Prototype", body: "Thinnest possible slice through the problem. Runs in your environment with real data.", time: "wks 3–6" },
        { num: "03", title: "Rollout", body: "Department by department. Telemetry, training, feedback loop. We stay involved.", time: "wks 7–12" },
        { num: "04", title: "Handover", body: "Clean code, documentation, optional support contract. Your team can extend it themselves.", time: "wk 13+" },
      ],
    },
    faq: {
      kicker: "FAQ",
      title: "What you were probably going to ask.",
      items: [
        { q: "Do we have to send all our data to an external LLM provider?", a: "No. We host in the EU by default, and use self-hosted models when compliance demands. Fully on-premise if needed." },
        { q: "What if AI isn't the right answer?", a: "Then we don't propose any. About half of our engagements end with classic software, better workflows, or an integration layer." },
        { q: "How does pricing work?", a: "Fixed price for the diagnostic (typically €12–25k). After that, fixed-price per module or T&M. The first call and a rough roadmap are free." },
        { q: "Do you also run it afterwards?", a: "Optionally. Three models: full handover, shared on-call, or managed service with SLA. No lock-in — the code is yours." },
        { q: "Which industries?", a: "Mid-market, industrial, healthcare, financial services, logistics. We turn down projects where we don't bring relevant experience." },
      ],
    },
    contact: {
      kicker: "Contact",
      title: "Let's talk for 30 minutes.",
      body: "First call no strings attached. If it's a fit, you get a rough roadmap and a fixed-price diagnostic quote within 5 business days.",
      checks: ["Reply within 24 hours", "NDA before the call if you need one", "No sales pressure"],
      f: { name: "Name", company: "Company", email: "Email", phone: "Phone (optional)", topic: "Topic", topicOpts: ["Process automation", "Chat / AI agent", "Security audit", "Custom software", "Something else"], message: "What's it about?", messagePh: "Briefly describe the bottleneck.", submit: "Request a call", thanks: "Thanks — we'll be in touch within 24 hours." },
    },
    footer: { copy: "© 2026 KI Welt GmbH — Hosted in Frankfurt a. M.", links: ["Imprint", "Privacy", "Careers"] },
  },
};
