// KI Welt — copy in DE + EN
export const COPY = {
  de: {
    nav: { home: "Start", services: "Leistungen", process: "Vorgehen", faq: "FAQ", contact: "Kontakt", cta: "Beratung buchen" },
    eyebrow: "KI Welt — Maßgeschneiderte KI für Unternehmen",
    primary: "Kostenlose Beratung buchen",
    secondary: "Alle Leistungen",
    nowLabel: "Anwendungsfall",
    beforeLabel: "Vorher",
    afterLabel: "Nachher",
    slides: [
      {
        tag: "Dokumenten­verarbeitung",
        h1Pre: "Aus Papierstapeln werden",
        h1Em: "Briefing-Mappen.",
        lede: "Eingang, OCR, strukturierte Zusammen­fassung, Auto-Routing zur richtigen Abteilung — mit Quellen­zitaten.",
        before: { label: "Vorher — manuell", value: "≈ 4 Std / Stapel" },
        after:  { label: "Nachher — KI Welt", value: "≈ 90 Sek / Stapel" },
      },
      {
        tag: "Kundenservice",
        h1Pre: "Ein Chat, der",
        h1Em: "wirklich handeln darf.",
        lede: "Ein Agent mit Zugriff auf Zahlung, CRM, E‑Mail und Versand. Antwortet, eskaliert klug, dokumentiert lückenlos.",
        before: { label: "Vorher — Hotline", value: "≈ 18 Min Wartezeit" },
        after:  { label: "Nachher — Agent", value: "≈ 22 Sek Erstantwort" },
      },
      {
        tag: "Sicherheit & Code",
        h1Pre: "Schwachstellen finden,",
        h1Em: "bevor andere sie finden.",
        lede: "Kontinuierliche Analyse statt Quartals-Audit. Priorisiert nach Ausnutzbarkeit — mit fertigen Pull-Requests.",
        before: { label: "Vorher — manuell", value: "1 × pro Quartal" },
        after:  { label: "Nachher — Audit", value: "Alle 4 Stunden" },
      },
      {
        tag: "Maßgeschneidert",
        h1Pre: "Vom Problem zum",
        h1Em: "eigenen Werkzeug.",
        lede: "Wir bauen die Anwendung — mit oder ohne KI — exakt für Ihren Prozess. Sauber dokumentiert, dann übergeben.",
        before: { label: "Vorher — Tool-Salat", value: "Excel-Stand: Donnerstag" },
        after:  { label: "Nachher — Eigenanwendung", value: "Live, Single Source" },
      },
    ],
    footer: { copy: "© 2026 KI Welt GmbH — Hosting in Frankfurt a. M.", links: ["Impressum", "Datenschutz", "Karriere"] },
  },

  en: {
    nav: { home: "Home", services: "Services", process: "Process", faq: "FAQ", contact: "Contact", cta: "Book a consultation" },
    eyebrow: "KI Welt — Custom AI for serious companies",
    primary: "Book a free consultation",
    secondary: "All services",
    nowLabel: "Use case",
    beforeLabel: "Before",
    afterLabel: "After",
    slides: [
      {
        tag: "Document processing",
        h1Pre: "Stacks of paper become",
        h1Em: "briefing folders.",
        lede: "Inbox, OCR, structured summary, auto-routing to the right department — with source citations.",
        before: { label: "Before — manual", value: "≈ 4h per batch" },
        after:  { label: "After — KI Welt", value: "≈ 90s per batch" },
      },
      {
        tag: "Customer service",
        h1Pre: "A chat that's actually",
        h1Em: "allowed to act.",
        lede: "One agent with access to payments, CRM, email, shipping. Answers, escalates intelligently, documents every step.",
        before: { label: "Before — hotline", value: "≈ 18 min wait" },
        after:  { label: "After — agent", value: "≈ 22s first reply" },
      },
      {
        tag: "Security & code",
        h1Pre: "Find the holes",
        h1Em: "before anyone else does.",
        lede: "Continuous analysis instead of quarterly audits. Prioritized by exploitability — with ready-to-merge pull requests.",
        before: { label: "Before — manual", value: "1× per quarter" },
        after:  { label: "After — audit", value: "every 4 hours" },
      },
      {
        tag: "Bespoke",
        h1Pre: "From problem to",
        h1Em: "your own tool.",
        lede: "We build the application — with or without AI — sized exactly for your process. Documented, then handed over.",
        before: { label: "Before — tool soup", value: "Excel as of: Thursday" },
        after:  { label: "After — own app", value: "live, single source" },
      },
    ],
    footer: { copy: "© 2026 KI Welt GmbH — Hosted in Frankfurt a. M.", links: ["Imprint", "Privacy", "Careers"] },
  },
};
